name: Deploy to Google Cloud Functions

on:
  push:
    branches:
      - main  # Cambia a la rama que prefieras usar para despliegues

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT }}
        service_account_key: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

    - name: Deploy to Google Cloud Functions
      run: |
        gcloud functions deploy helloWorld \
          --runtime nodejs20 \
          --trigger-http \
          --allow-unauthenticated \
          --gen2 \
          --region southamerica-east1
